using System;
using System.Collections.Generic;
using System.Text;

namespace LookaukwatApp.ViewModels.StaticList
{
    public class StaticListHouseViewModel
    {
        public static List<string> GetRubriqueHouseListt = new List<string>
        {
            "Ameublement",
"Electroménager",
"Cuisine",
"Décoration",
"Linge de maison",
"Bricolage",
"Jardinage"
        };
        public static List<string> GetTypeAmebleumentHouseList = new List<string>
        {
            "Accessoire",
"Armoire",
"Bar",
"Bain & baignoire",
"Bibliothèque et étagère",
"Buffet",
"Bureau",
"Canapé",
"Canapé convertible et clic clac",
"Chaise, tabouret et banc",
"Coffre et malle",
"Coiffeuse",
"Commode",
"Console",
"Dressing et penderie",
"Fauteuil",
"Lit",
"Lit pour enfant",
"Luminaire",
"Matelas",
"Meuble de cuisine",
"Meuble de jardin",
"Meuble de rangement",
"Meuble de salle de bain",
"Meuble TV",
"Porte",
"Porte-manteau",
"Sommier",
"Table d'appoint",
"Table de salle à manger",
"Table basse",
"Table de chevet",
"Tapis",
"Vaisselier",
"Autre"
        };
        public static List<string> GetFabricMaterialAmmeblementDecorationList = new List<string>
        {
            "Acier",
"Bois",
"Bois massif",
"Bronze",
"Céramique",
"Chêne",
"Cuir",
"Fer",
"Formica",
"Laqué",
"Marbre",
"Métal",
"Pierre",
"Pin",
"Plastique",
"Rotin et osier",
"Tissu",
"Velours",
"Verre",
"Autre"
        };
        public static List<string> GetTypeOutilTableHouseList = new List<string>
        {
            "Assiette",
"Beurrier",
"Bocaux et pots",
"Boite de conservation et boite en métal",
"Bol",
"Bonbonnière",
"Carafe et pichet",
"Casserole",
"Cocotte",
"Coffret",
"Coquetier",
"Corbeille",
"Coupe et coupelle",
"Couteaux",
"Couvercle",
"Couvert",
"Dessous de plat",
"Flûte",
"Gourde",
"Huilier et vinaigrier",
"Mazagran",
"Moule",
"Planche à découper",
"Plat à four et à tarte",
"Plat apéritif",
"Plat de service",
"Plateau",
"Poële",
"Ramequin",
"Rond de serviette",
"Saladier",
"Salière, poivrière et sucrier",
"Saucière",
"Seau à glaçons",
"Service à café ou à thé",
"Service de vaisselle",
"Set de table",
"Shaker",
"Soucoupe",
"Soupière",
"Sous verre",
"Tasse et mug",
"Terrine",
"Théière, tisanière",
"Tire-bouchon",
"Ustensile de cuisine",
"Verre",
"Verrine",
"Autre"
        };
        public static List<string> GetTypeDecorationHouseList = new List<string>
        {
            "Abat-jour",
"Accessoire de rangement",
"Accessoire de salle de bain",
"Applique",
"Bibelot",
"Bougeoir et photophore",
"Bouquet et plante artificielle",
"Cadre photo",
"Cendrier et vide-poche",
"Coussin",
"Dame-jeanne et bonbonne",
"Guirlande",
"Horloge, pendule et réveil",
"Lampadaire",
"Lampe à poser",
"Lampe sur pied",
"Lustre",
"Miroir",
"Panier, boite",
"Paravent",
"Pêle-mêle photo",
"Rideaux, voilage et store",
"Sculpture et statue",
"Suspension",
"Tableau et toile",
"Tapis",
"Vase, cache pot et céramique",
"Autre"
        };
        public static List<string> GetFabricMaterialOutilTableList = new List<string>
        {
            "Acrylique",
"Alu",
"Argenterie",
"Bambou",
"Bois",
"Caoutchouc",
"Carton",
"Céramique",
"Coton",
"Cristal",
"Cuivre",
"Faïence",
"Fer forgé",
"Grès",
"Inox",
"Métal",
"Papier",
"Pierre",
"Plastique",
"Polyester",
"Porcelaine",
"PVC",
"Résine",
"Terre cuite",
"Verre",
"Autre"
        };
        public static List<string> GetTypeLingeHouseList = new List<string>
        {
            "Linge de lit",
"Linge de bain",
"Déco textile",
"Linge de table",
"Équipement du lit",
"Autre"
        };
        public static List<string> GetFabricMaterialLingeList = new List<string>
        {
            "Coton",
"Coton biologique",
"Lin",
"PVC et synthétique",
"Velours",
"Laine",
"Fausse fourrure",
"Fibres Naturelles",
"Papier",
"Viscose",
"Satin de coton",
"Percale de coton",
"Toile ciré",
"Polyester, Polyester/Coton",
"Flanelle",
"Métis",
"Autre"
        };
        public static List<string> GetStateHouseList = new List<string>
        {
            "État neuf",
"Très bon étatussures",
"Bon état",
"État satisfaisant",
"Pour pièces"
        };


        ///////////////////////////////For  Search        ////////////////////////////////

       
            public static List<string> GetRubriqueHouseListtSearch = new List<string>
        {
            "Toutes",
            "Ameublement",
"Electroménager",
"Cuisine",
"Décoration",
"Linge de maison",
"Bricolage",
"Jardinage"
        };
            public static List<string> GetTypeAmebleumentHouseListSearch = new List<string>
        {
            "Tout",
            "Accessoire",
"Armoire",
"Bar",
"Bain & baignoire",
"Bibliothèque et étagère",
"Buffet",
"Bureau",
"Canapé",
"Canapé convertible et clic clac",
"Chaise, tabouret et banc",
"Coffre et malle",
"Coiffeuse",
"Commode",
"Console",
"Dressing et penderie",
"Fauteuil",
"Lit",
"Lit pour enfant",
"Luminaire",
"Matelas",
"Meuble de cuisine",
"Meuble de jardin",
"Meuble de rangement",
"Meuble de salle de bain",
"Meuble TV",
"Porte",
"Porte-manteau",
"Sommier",
"Table d'appoint",
"Table de salle à manger",
"Table basse",
"Table de chevet",
"Tapis",
"Vaisselier",
"Autre"
        };
            public static List<string> GetFabricMaterialAmmeblementDecorationListSearch = new List<string>
        {
            "Tout",
            "Acier",
"Bois",
"Bois massif",
"Bronze",
"Céramique",
"Chêne",
"Cuir",
"Fer",
"Formica",
"Laqué",
"Marbre",
"Métal",
"Pierre",
"Pin",
"Plastique",
"Rotin et osier",
"Tissu",
"Velours",
"Verre",
"Autre"
        };
            public static List<string> GetTypeOutilTableHouseListSearch = new List<string>
        {
            "Tout",
            "Assiette",
"Beurrier",
"Bocaux et pots",
"Boite de conservation et boite en métal",
"Bol",
"Bonbonnière",
"Carafe et pichet",
"Casserole",
"Cocotte",
"Coffret",
"Coquetier",
"Corbeille",
"Coupe et coupelle",
"Couteaux",
"Couvercle",
"Couvert",
"Dessous de plat",
"Flûte",
"Gourde",
"Huilier et vinaigrier",
"Mazagran",
"Moule",
"Planche à découper",
"Plat à four et à tarte",
"Plat apéritif",
"Plat de service",
"Plateau",
"Poële",
"Ramequin",
"Rond de serviette",
"Saladier",
"Salière, poivrière et sucrier",
"Saucière",
"Seau à glaçons",
"Service à café ou à thé",
"Service de vaisselle",
"Set de table",
"Shaker",
"Soucoupe",
"Soupière",
"Sous verre",
"Tasse et mug",
"Terrine",
"Théière, tisanière",
"Tire-bouchon",
"Ustensile de cuisine",
"Verre",
"Verrine",
"Autre"
        };
            public static List<string> GetTypeDecorationHouseListSearch = new List<string>
        {
            "Tout",
            "Abat-jour",
"Accessoire de rangement",
"Accessoire de salle de bain",
"Applique",
"Bibelot",
"Bougeoir et photophore",
"Bouquet et plante artificielle",
"Cadre photo",
"Cendrier et vide-poche",
"Coussin",
"Dame-jeanne et bonbonne",
"Guirlande",
"Horloge, pendule et réveil",
"Lampadaire",
"Lampe à poser",
"Lampe sur pied",
"Lustre",
"Miroir",
"Panier, boite",
"Paravent",
"Pêle-mêle photo",
"Rideaux, voilage et store",
"Sculpture et statue",
"Suspension",
"Tableau et toile",
"Tapis",
"Vase, cache pot et céramique",
"Autre"
        };
            public static List<string> GetFabricMaterialOutilTableListSearch = new List<string>
        {
            "Toute",
            "Acrylique",
"Alu",
"Argenterie",
"Bambou",
"Bois",
"Caoutchouc",
"Carton",
"Céramique",
"Coton",
"Cristal",
"Cuivre",
"Faïence",
"Fer forgé",
"Grès",
"Inox",
"Métal",
"Papier",
"Pierre",
"Plastique",
"Polyester",
"Porcelaine",
"PVC",
"Résine",
"Terre cuite",
"Verre",
"Autre"
        };
            public static List<string> GetTypeLingeHouseListSearch = new List<string>
        {
            "Tout",
            "Linge de lit",
"Linge de bain",
"Déco textile",
"Linge de table",
"Équipement du lit",
"Autre"
        };
            public static List<string> GetFabricMaterialLingeListSearch = new List<string>
        {
            "tout",
            "Coton",
"Coton biologique",
"Lin",
"PVC et synthétique",
"Velours",
"Laine",
"Fausse fourrure",
"Fibres Naturelles",
"Papier",
"Viscose",
"Satin de coton",
"Percale de coton",
"Toile ciré",
"Polyester, Polyester/Coton",
"Flanelle",
"Métis",
"Autre"
        };
            public static List<string> GetStateHouseListSearch = new List<string>
        {
            "Tout",
            "État neuf",
"Très bon étatussures",
"Bon état",
"État satisfaisant",
"Pour pièces"
        };

        }
}
