using System;
using System.Collections.Generic;
using System.Text;

namespace LookaukwatApp.ViewModels.StaticList
{
    public class StaticListModeViewModel
    {

        public static List<string> GetRubriqueModeList = new List<string>
        {
            "Vêtements",
            "Chaussures",
            "Accesoires & Bagagerie",
            "Montres & Bijoux",
            "Equipement bébé",
            "Vêtements bébé"
        };

        public static List<string> GetTypeClothesList = new List<string>
        {
            "Robes/Jupes",
"Manteaux & Vestes",
"Hauts/T-Shirts/Polos",
"Pantalons",
"Pulls/Gilets/Mailles",
"Jeans",
"Chemises/Chemisiers",
"Costumes/Tailleurs",
"Shorts/Pantacourts/Bermudas",
"Sport/Danse",
"Maillots de bain/vêtements de plage",
"Lingerie",
"Sous-vêtements & vêtements de nuit",
"Déguisements",
"Mariage",
        };

        public static List<string> GetTypeShoesList = new List<string>
        {
            "Baskets/Sneakers",
"Chaussures à lacets",
"Chaussures à scratch",
"Mocassins",
"Bottines & lowboots",
"Bottes",
"Escarpins",
"Sandales & Nu-pieds",
"Chaussons & Pantoufles",
"Ballerines",
"Autre",
        };

        public static List<string> GetTypeAccesorieLugagesList = new List<string>
        {
            "Accessoire pour cheveux",
"Bonnet, bob, béret",
"Bretelles",
"Cartable",
"Casquette",
"Ceinture",
"Châle et étole",
"Chapeau",
"Cravate et noeud papillon",
"Echarpe et foulard",
"Etui téléphone",
"Gants, mitaines et moufles",
"Housse de tablette et ordinateur",
"Lunettes",
"Mallette",
"Parapluie",
"Perruque",
"Pochette",
"Porte-cartes",
"Porte-chéquier",
"Porte-clés",
"Porte-habits",
"Porte-monnaie et portefeuille",
"Sac à dos",
"Sac à main",
"Sac de voyage",
"Sac en bandoulière",
"Sacoche",
"Trousse",
"Valise cabine",
"Valise moyenne et grande taille",
"Autre",
        };

        public static List<string> GetTypeWatchJewelryList = new List<string>
        {
            "Bague",
"Bijou de téléphone",
"Bijou de tête",
"Boucles d'oreilles",
"Boutons de manchette",
"Bracelet",
"Broche",
"Chaîne",
"Charm",
"Chevalière",
"Collier, pendentif",
"Gourmette",
"Montre à gousset",
"Montre automatique",
"Montre connectée",
"Montre de sport",
"Montre mécanique",
"Montre quartz",
"Montre-bague",
"Montre-pendentif",
"Parure",
"Piercing",
"Autre",
        };

        public static List<string> GetTypeBabyEquipmentList = new List<string>
        {
            "Babyphone",
"Baignoire",
"Barrière de sécurité",
"Bavoir",
"Berceau",
"Biberon",
"Chaise haute",
"Chancelière",
"Chauffe-biberon",
"Couffin",
"Coussin d'allaitement",
"Gigoteuse",
"Humidificateur",
"Lit bébé",
"Lit parapluie",
"Matelas et matelas à langer",
"Nacelle",
"Nid d'ange",
"Parc",
"Porte-bébé et écharpe de portage",
"Poubelle à couches",
"Poussette",
"Pot et siège réducteur",
"Rehausseur",
"Robot de cuisine bébé",
"Sac à langer",
"Sécurité domestique",
"Sécurité extérieur",
"Siège auto",
"Stérilisateur",
"Sucette",
"Table à langer",
"Tapis d'éveil",
"Tétine",
"Thermomètre",
"Tire-lait",
"Transat et balancelle",
"Trotteur",
"Vaisselle",
"Veilleuse",
"Autre",
        };

        public static List<string> GetTypeBabyClothesList = new List<string>
        {
            "Bodies",
"T-shirt & brassières",
"Bermudas & Shorts",
"Pantalons",
"Jeans",
"Dors-bien & Pyjamas",
"Pull & Gilets",
"Robes & Jupes",
"Manteaux & Vestes",
"Legging & collants",
"Déguisements",
"Ensembles & Combinaisons",
"Bonnets & Chapeaux",
"Maillots de bain",
"Autre",
        };
        public static List<string> GetBrandClothesList = new List<string>
        {
            "Adidas",
"Armani",
"Balenciaga",
"BCBG Max Azria",
"Bershka",
"Burberry",
"C&A",
"Calvin Klein",
"Camaieu",
"Canada Goose",
"Celio",
"Chanel",
"Desigual",
"Diesel",
"Dior",
"Dolce & Gabbana",
"Esprit",
"Etam",
"Givenchy",
"G-Star",
"Gucci",
"Guess",
"H&M",
"Hugo Boss",
"Jack & Jones",
"ean Paul Gaultie",
"Kaporal",
"Kappa",
"Kenzo",
"Lacoste",
"Levi's",
"Louis Vuitton",
"Mango",
"Nike",
"Zara",
"Autre",
        };
        public static List<string> GetBrandShoesList = new List<string>
        {
            "Adidas",
"Asics",
"Azzaro",
"Balenciaga",
"Bensimon",
"Bexley",
"Calvin Klein",
"Celio",
"Chanel",
"Christian Louboutin",
"Clarks",
"Converse",
"Coq Sportif",
"Dc Shoes",
"Desigual",
"Dior",
"Ellesse",
"Geox",
"Giuseppe Zanotti",
"Gucci",
"Guess",
"H&M",
"Hugo Boss",
"Jm Weston",
"Kappa",
"Lacoste",
"Levis",
"Louis Vuitton",
"New Balance",
"Nike",
"Palladium",
"Paul Smith",
"Prada",
"Puma",
"Ralph Lauren",
"Reebok",
"Timberland",
"Vans",
"Weston",
"Zara",
"Autre",
        };
        public static List<string> GetUniversList = new List<string>
        {
            "Femme",
"Maternité",
"Mixte",
"Homme",
"Enfant",
        };
        public static List<string> GetSeizeClothesList = new List<string>
        {
            "Prématuré",
"0 mois",
"1 mois",
"5 mois",
"10 mois",
"15 mois",
"25 mois",
"3 ans",
"4 ans",
"5 ans",
"6 ans",
"7 ans",
"8 ans",
"9 ans",
"10 ans",
"12 ans",
"14 ans",
"32 - XXS",
"34 - XS",
"36 - S",
"38 - M",
"40 - L",
"42 - XL",
"44 - XXL",
"46 - XXXL",
"48 - 4XL",
"50 et plus - 5XL",

        };
        public static List<string> GetSizeShoesList = new List<string>
        {
"16",
"18",
"19",
"20",
"21",
"22",
"23",
"24",
"25",
"26",
"27",
"28",
"29",
"30",
"31",
"32",
"33",
"34",
"35",
"36",
"37",
"38",
"39",
"40",
"41",
"42",
"43",
"44",
"45",
"46",
"47",
"48",
"49",
"50+",
        };
        public static List<string> GetColorModeList = new List<string>
        {
            "Argenté / Acier",
"Beige / Camel",
"Blanc",
"Bleu / Ciel",
"Crème / Blanc cassé / Écru",
"Doré / Bronze / Cuivre",
"Gris / Anthracite",
"Imprimés multicolore",
"Jaune / Moutarde",
"Kaki",
"Lavande / Lilas",
"Marine / Turquoise",
"Multicolore",
"Noir",
"Orange / Corail",
"Rose / Fushia",
"Rouge / Bordeaux",
"Vert",
"Violet / Mauve",
"Autre",
        };
        public static List<string> GetStateModeList = new List<string>
        {
            "Neuf avec étiquette",
"Neuf sans étiquette",
"Très bon état",
"Bon état",
"État satisfaisant"
        };

        //////////////////////////For Search /////////////////////////


        public static List<string> GetRubriqueModeListSearch = new List<string>
        {
            "Toutes",
            "Vêtements",
            "Chaussures",
            "Accesoires & Bagagerie",
            "Montres & Bijoux",
            "Equipement bébé",
            "Vêtements bébé"
        };

        public static List<string> GetTypeClothesListSearch = new List<string>
        {
            "Tout",
            "Robes/Jupes",
"Manteaux & Vestes",
"Hauts/T-Shirts/Polos",
"Pantalons",
"Pulls/Gilets/Mailles",
"Jeans",
"Chemises/Chemisiers",
"Costumes/Tailleurs",
"Shorts/Pantacourts/Bermudas",
"Sport/Danse",
"Maillots de bain/vêtements de plage",
"Lingerie",
"Sous-vêtements & vêtements de nuit",
"Déguisements",
"Mariage",
        };

        public static List<string> GetTypeShoesListSearch = new List<string>
        {
            "Tout",
            "Baskets/Sneakers",
"Chaussures à lacets",
"Chaussures à scratch",
"Mocassins",
"Bottines & lowboots",
"Bottes",
"Escarpins",
"Sandales & Nu-pieds",
"Chaussons & Pantoufles",
"Ballerines",
"Autre",
        };

        public static List<string> GetTypeAccesorieLugagesListSearch = new List<string>
        {
            "Tout",
            "Accessoire pour cheveux",
"Bonnet, bob, béret",
"Bretelles",
"Cartable",
"Casquette",
"Ceinture",
"Châle et étole",
"Chapeau",
"Cravate et noeud papillon",
"Echarpe et foulard",
"Etui téléphone",
"Gants, mitaines et moufles",
"Housse de tablette et ordinateur",
"Lunettes",
"Mallette",
"Parapluie",
"Perruque",
"Pochette",
"Porte-cartes",
"Porte-chéquier",
"Porte-clés",
"Porte-habits",
"Porte-monnaie et portefeuille",
"Sac à dos",
"Sac à main",
"Sac de voyage",
"Sac en bandoulière",
"Sacoche",
"Trousse",
"Valise cabine",
"Valise moyenne et grande taille",
"Autre",
        };

        public static List<string> GetTypeWatchJewelryListSearch = new List<string>
        {
            "Tout",
            "Bague",
"Bijou de téléphone",
"Bijou de tête",
"Boucles d'oreilles",
"Boutons de manchette",
"Bracelet",
"Broche",
"Chaîne",
"Charm",
"Chevalière",
"Collier, pendentif",
"Gourmette",
"Montre à gousset",
"Montre automatique",
"Montre connectée",
"Montre de sport",
"Montre mécanique",
"Montre quartz",
"Montre-bague",
"Montre-pendentif",
"Parure",
"Piercing",
"Autre",
        };

        public static List<string> GetTypeBabyEquipmentListSearch = new List<string>
        {
            "Tout",
            "Babyphone",
"Baignoire",
"Barrière de sécurité",
"Bavoir",
"Berceau",
"Biberon",
"Chaise haute",
"Chancelière",
"Chauffe-biberon",
"Couffin",
"Coussin d'allaitement",
"Gigoteuse",
"Humidificateur",
"Lit bébé",
"Lit parapluie",
"Matelas et matelas à langer",
"Nacelle",
"Nid d'ange",
"Parc",
"Porte-bébé et écharpe de portage",
"Poubelle à couches",
"Poussette",
"Pot et siège réducteur",
"Rehausseur",
"Robot de cuisine bébé",
"Sac à langer",
"Sécurité domestique",
"Sécurité extérieur",
"Siège auto",
"Stérilisateur",
"Sucette",
"Table à langer",
"Tapis d'éveil",
"Tétine",
"Thermomètre",
"Tire-lait",
"Transat et balancelle",
"Trotteur",
"Vaisselle",
"Veilleuse",
"Autre",
        };

        public static List<string> GetTypeBabyClothesListSearch = new List<string>
        {
            "Tout",
            "Bodies",
"T-shirt & brassières",
"Bermudas & Shorts",
"Pantalons",
"Jeans",
"Dors-bien & Pyjamas",
"Pull & Gilets",
"Robes & Jupes",
"Manteaux & Vestes",
"Legging & collants",
"Déguisements",
"Ensembles & Combinaisons",
"Bonnets & Chapeaux",
"Maillots de bain",
"Autre",
        };
        public static List<string> GetBrandClothesListSearch = new List<string>
        {
            "Toutes",
            "Adidas",
"Armani",
"Balenciaga",
"BCBG Max Azria",
"Bershka",
"Burberry",
"C&A",
"Calvin Klein",
"Camaieu",
"Canada Goose",
"Celio",
"Chanel",
"Desigual",
"Diesel",
"Dior",
"Dolce & Gabbana",
"Esprit",
"Etam",
"Givenchy",
"G-Star",
"Gucci",
"Guess",
"H&M",
"Hugo Boss",
"Jack & Jones",
"ean Paul Gaultie",
"Kaporal",
"Kappa",
"Kenzo",
"Lacoste",
"Levi's",
"Louis Vuitton",
"Mango",
"Nike",
"Zara",
"Autre",
        };
        public static List<string> GetBrandShoesListSearch = new List<string>
        {
            "Toutes",
            "Adidas",
"Asics",
"Azzaro",
"Balenciaga",
"Bensimon",
"Bexley",
"Calvin Klein",
"Celio",
"Chanel",
"Christian Louboutin",
"Clarks",
"Converse",
"Coq Sportif",
"Dc Shoes",
"Desigual",
"Dior",
"Ellesse",
"Geox",
"Giuseppe Zanotti",
"Gucci",
"Guess",
"H&M",
"Hugo Boss",
"Jm Weston",
"Kappa",
"Lacoste",
"Levis",
"Louis Vuitton",
"New Balance",
"Nike",
"Palladium",
"Paul Smith",
"Prada",
"Puma",
"Ralph Lauren",
"Reebok",
"Timberland",
"Vans",
"Weston",
"Zara",
"Autre",
        };
        public static List<string> GetUniversListSearch = new List<string>
        {
            "Tout",
            "Femme",
"Maternité",
"Mixte",
"Homme",
"Enfant",
        };
        public static List<string> GetSeizeClothesListSearch = new List<string>
        {
            "Toutes",
            "Prématuré",
"0 mois",
"1 mois",
"5 mois",
"10 mois",
"15 mois",
"25 mois",
"3 ans",
"4 ans",
"5 ans",
"6 ans",
"7 ans",
"8 ans",
"9 ans",
"10 ans",
"12 ans",
"14 ans",
"32 - XXS",
"34 - XS",
"36 - S",
"38 - M",
"40 - L",
"42 - XL",
"44 - XXL",
"46 - XXXL",
"48 - 4XL",
"50 et plus - 5XL",

        };
        public static List<string> GetSizeShoesListSearch = new List<string>
        {
"Toutes",
"16",
"18",
"19",
"20",
"21",
"22",
"23",
"24",
"25",
"26",
"27",
"28",
"29",
"30",
"31",
"32",
"33",
"34",
"35",
"36",
"37",
"38",
"39",
"40",
"41",
"42",
"43",
"44",
"45",
"46",
"47",
"48",
"49",
"50+",
        };
        public static List<string> GetColorModeListSearch = new List<string>
        {
            "Toutes",
            "Argenté / Acier",
"Beige / Camel",
"Blanc",
"Bleu / Ciel",
"Crème / Blanc cassé / Écru",
"Doré / Bronze / Cuivre",
"Gris / Anthracite",
"Imprimés multicolore",
"Jaune / Moutarde",
"Kaki",
"Lavande / Lilas",
"Marine / Turquoise",
"Multicolore",
"Noir",
"Orange / Corail",
"Rose / Fushia",
"Rouge / Bordeaux",
"Vert",
"Violet / Mauve",
"Autre",
        };
        public static List<string> GetStateModeListSearch = new List<string>
        {
            "Tout",
            "Neuf avec étiquette",
"Neuf sans étiquette",
"Très bon état",
"Bon état",
"État satisfaisant"
        };
    }
}
